dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.3

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.3'

reports:
  exclude_contracts:
    - ERC20
    - ERC721
    - Ownable
    - ReentrancyGuard